spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:lostarkdb;NON_KEYWORDS=USER;DATABASE_TO_UPPER=FALSE

spring.datasource.driver-className=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

lostark.api.url=https://developer-lostark.game.onstove.com
lostark.api.key=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyIsImtpZCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyJ9.eyJpc3MiOiJodHRwczovL2x1ZHkuZ2FtZS5vbnN0b3ZlLmNvbSIsImF1ZCI6Imh0dHBzOi8vbHVkeS5nYW1lLm9uc3RvdmUuY29tL3Jlc291cmNlcyIsImNsaWVudF9pZCI6IjEwMDAwMDAwMDAwODk1NTQifQ.c7ipc0xD2U0OAjeSR3mgjghFA-FnOVaPEt2-7jxmZP2Yj607uGXME6wGWHsPbWIboR6kVhxwmngqgmb-wAD_D1hHq-nXZ5YsIQOjEg7tZuV110ycvY9aKP9mtyKnrcQXVNmbGFy4QVikt4xjflNYuDfsNfj8FL01LfyBtn_jAegkFOsIKXAgQPGK6nfHDVxD4fAxqZ_3t-s-AOPqybyeg3QMP4_tjmKIOKYKffs1vZyBgGjhv_6FlKOwah3kwkqwvoQgAnc926g7UjgmjFgLTNBRc8lkXmXIMZyggDlQXFIYbb1_5hS2EaFuc8Djv4p1yDNuDrnanS8yPzKSIGu19g;